version: "3"
services:
    apitest:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        #volumes: 
        #    - /node_modules
        #    - .:/


# BUILD
# sudo docker-compose up --build