# DEVELOPMENT VERSION
FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# Copy All Files :)
COPY . .

EXPOSE 80

CMD ["npm", "run", "dev"]

# sudo docker build -f Dockerfile.dev .
# Successfully built 07f4709dd24c
# sudo docker run -ti -p 80:80 ID_GERADO